# SqrtPI Rice v0
$scrPath=$HOME/sqrtPI/Scripts

# Source things at the top so they can be overwritten if needed
source = ./hyprselect.conf
source = ./keybindings.conf # Keyboard Shortcuts
source = ./windowrules.conf
source = ./monitors.conf # Monitor configuration (dont really need to use, its very simple)
#source = ./variables.conf # Variable import (might not use, currently does not exist)
source = ./sq-hyprland.conf

$CURSOR_THEME=Bibata-Modern-Ice
$CURSOR_SIZE=24

# System thingys
exec-once = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE
exec-once = waybar
exec-once = hypridle
exec-once = hyprpaper

# Run to fix OBS virtual cam (not in this file, its just the process)
# Automatically on startup forever: echo "v4l2loopback" | sudo tee /etc/modules-load.d/load-v4l2loopback.conf
# Manually for the current session: sudo modprobe v4l2loopback

# From the hyprland tutorial to get screenshare working (didnt work + use vesktop and build your own vencord)
#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = xwaylandvideobridge
# From https://www.lorenzobettini.it/2023/07/hyprland-getting-started-part-2/
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# From troubleshooting
exec-once = /usr/lib/hyprpolkitagent

# Window rule for freerdp3 for functionality: https://github.com/hyprwm/Hyprland/issues/6427
windowrule = tile on, no_max_size on, match:class sdl-freerdp3 #, match:title ^(WindowsRDP)$

###
### Hyprland Variable Configurations
### https://wiki.hypr.land/Configuring/Variables
###

dwindle {
    pseudotile = yes
    preserve_split = yes
}

general {
    no_focus_fallback=true # Stops focus wrapping, which is usually unintuitive
    layout = dwindle
}

# 3-finger swipe to move between workspaces
gestures {
    gesture = 3, horizontal, workspace
}

input {
    # kb_layout = us
    # follow_mouse = 1
    force_no_accel = 1 # mouse accelleration is evil
    accel_profile = flat # mouse accelleration is evil x2
    # numlock_by_default = true
    # See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
    }
}

