# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground            #d56c95
#foreground            #A5F5EA
background            #1a1520
cursor                #D56C95
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

wayland_titlebar_color system

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# Black
color0                #2d2433
color8                #4a3d52

# Red
color1                #E85B54
color9                #ff7a72

# Green
color2                #7ce0d3
color10               #A5F5EA

# Yellow
color3                #ffc4b5
color11               #ffd9cc

# Blue
color4                #c57b9a
color12               #e89bb8

# Magenta
color5                #D56C95
color13               #ed8cb1

# Cyan
color6                #8ff0e6
color14               #bff8f0

# White
color7                #FBB4A2
color15               #ffe5dc
