# SqrtPI Rice v0
$scrPath=$HOME/sqrtPI/Scripts

# Check monitors with: hyprctl monitors
# Note: Monitor "order" is left->right in terms of the phsyical GPU connection. For nvidia cards this
#   is usually in the order of (HDMI-A-0, DP-1, DP-2, DP-3). Keep this in mind while positioning things.
#monitor = DP-1, 3840x2160@120, 0x0, 1.5 #left monitor 4k
monitor = DP-1, 2560x1440@240, 0x0, 1, bitdepth, 10 #left monitor 2k
#monitor = DP-1, 1920x1080@240, 0x0, 1, bitdepth, 10 #left monitor 2k
monitor = HDMI-A-1, 2560x1440@144, auto-right, 1 #right monitor 2k

# Workspaces for each individual monitor.
# Reasoning: 1 is main wokring, 2 is secondary working, 5 is fullscreen applications for main
#   3 is generally static (music, messaging app), 4 and 6 are overflow 
#workspace = 1, monitor:DP-1, default:true
#workspace = 2, monitor:DP-1
#workspace = 3, monitor:HDMI-A-1, default:true
#workspace = 4, monitor:HDMI-A-1
#workspace = 5, monitor:DP-1
#workspace = 6, monitor:HDMI-A-1 
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1 

# Source things at the top so they can be overwritten if needed
source = ./hyprselect.conf
source = ./keybindings.conf # Keyboard Shortcuts
source = ./windowrules.conf
#source = ./monitors.conf # Monitor configuration (dont really need to use, its very simple)
#source = ./variables.conf # Variable import (might not use, currently does not exist)
source = ./sq-hyprland.conf

$CURSOR_THEME=Bibata-Modern-Ice
$CURSOR_SIZE=24

# System thingys
exec-once = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE
exec-once = waybar
exec-once = hypridle
exec-once = hyprpaper

# Run to fix OBS virtual cam (not in this file, its just the process)
# Automatically on startup forever: echo "v4l2loopback" | sudo tee /etc/modules-load.d/load-v4l2loopback.conf
# Manually for the current session: sudo modprobe v4l2loopback

# From the hyprland tutorial to get screenshare working (didnt work + use vesktop and build your own vencord)
#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = xwaylandvideobridge
# From https://www.lorenzobettini.it/2023/07/hyprland-getting-started-part-2/
#exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Window rule for freerdp3 for functionality: https://github.com/hyprwm/Hyprland/issues/6427
windowrule = tile on, no_max_size on, match:class sdl-freerdp3 #, match:title ^(WindowsRDP)$

###
### Hyprland Variable Configurations
### https://wiki.hypr.land/Configuring/Variables
###

dwindle {
    pseudotile = yes
    preserve_split = yes
}

general {
    no_focus_fallback=true # Stops focus wrapping, which is usually unintuitive
}

input {
    # kb_layout = us
    # follow_mouse = 1
    force_no_accel = 1 # mouse accelleration is evil
    accel_profile = flat # mouse accelleration is evil x2
    # numlock_by_default = true
    # See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }
}

