source-file /home/cj/.sq-tmux.conf

set-option -g default-shell /usr/bin/zsh
set -g mouse on

set -g allow-passthrough on

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
