
# The basic colors
foreground              #cdd6f4
background              #121219
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# Normal colors
color0  #0f100f
color1  #625F31
color2  #384A47
color3  #615847
color4  #726B49
color5  #A66532
color6  #8F7350
color7  #d5c0a4

# Bright colors
color8  #958672
color9  #625F31
color10 #384A47
color11 #615847
color12 #726B49
color13 #A66532
color14 #8F7350
color15 #d5c0a4
